export const products = [
	{
		id: "p1",
		name: "Minimal A5 Notebook",
		price: 299,
		original_price: 399,
		on_sale: true,
		url: "/products/minimal-a5-notebook",
		image_url: "/images/notebook-a5.webp",
		alt: "Minimal A5 notebook with soft beige cover",
	},
	{
		id: "p2",
		name: "Pastel Highlighter Set (Pack of 6)",
		price: 249,
		url: "/products/pastel-highlighters",
		image_url: "/images/highlighters.webp",
		alt: "Set of 6 pastel highlighters",
	},
	{
		id: "p3",
		name: "Premium Gel Pen - Blue Ink",
		price: 49,
		original_price: 79,
		on_sale: true,
		url: "/products/gel-pen-blue",
		image_url: "/images/gel-pen.webp",
		alt: "Smooth writing blue gel pen",
	},
	{
		id: "p4",
		name: "Vintage Postcard Collection (Set of 10)",
		price: 199,
		url: "/products/vintage-postcards",
		image_url: "/images/postcards.webp",
		alt: "Vintage aesthetic postcards set",
	},
	{
		id: "p5",
		name: "Desk Organizer Tray",
		price: 499,
		url: "/products/desk-organizer",
		image_url: "/images/desk-organizer.webp",
		alt: "Wooden desk organizer tray",
	},
	{
		id: "p6",
		name: "Floral Sticker Pack (50 pcs)",
		price: 149,
		original_price: 199,
		on_sale: true,
		url: "/products/floral-stickers",
		image_url: "/images/stickers-floral.webp",
		alt: "Floral themed decorative stickers",
	},
	{
		id: "p7",
		name: "Hardcover Bullet Journal",
		price: 599,
		url: "/products/bullet-journal",
		image_url: "/images/bullet-journal.webp",
		alt: "Hardcover dotted bullet journal",
	},
	{
		id: "p8",
		name: "Calligraphy Brush Pen Set",
		price: 349,
		url: "/products/brush-pen-set",
		image_url: "/images/brush-pens.webp",
		alt: "Set of brush pens for calligraphy",
	},
];
